spring:
  application:
    name: security7-practice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33062/security7?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  mustache:
    servlet:
      expose-request-attributes: true

app:
  security:
    remember-me:
      key: jdaj921jioe91jkasmi120diaklsdnml90adhu

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 1800

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace